# Generated by Django 2.2 on 2020-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='decrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_image', models.ImageField(upload_to='')),
                ('result', models.ImageField(blank=True, null=True, upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
