# Generated by Django 2.2 on 2020-11-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypt',
            name='using',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
